name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: WordPress Plugin Deploy
        uses: wpsetter/action-wordpress-plugin-deploy@develop
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_URL: 'https://wpsetter.svn.beanstalkapp.com/test-github-actions/'
          SLUG: test-github-actions